//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class district
    {
        public district()
        {
            this.sub_district = new HashSet<sub_district>();
        }
    
        public int district_id { get; set; }
        public string district_name { get; set; }
        public int division_id { get; set; }
    
        public virtual division division { get; set; }
        public virtual ICollection<sub_district> sub_district { get; set; }
    }
}
