//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_religion
    {
        public student_religion()
        {
            this.admission_form = new HashSet<admission_form>();
        }
    
        public int student_religion_id { get; set; }
        public string student_religion_name { get; set; }
    
        public virtual ICollection<admission_form> admission_form { get; set; }
    }
}
