//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_info
    {
        public student_info()
        {
            this.results = new HashSet<result>();
        }
    
        public int student_id { get; set; }
        public string student_full_name { get; set; }
        public string student_father_name { get; set; }
        public string student_mother_name { get; set; }
        public string student_father_mobile_number { get; set; }
        public string student_address { get; set; }
        public string student_mobile_number { get; set; }
        public string student_email { get; set; }
        public int student_department_id { get; set; }
        public string student_image { get; set; }
        public System.DateTime student_dob { get; set; }
        public string student_session { get; set; }
        public System.DateTime student_passing_year { get; set; }
        public string student_hsc_roll { get; set; }
        public string student_hsc_registration_no { get; set; }
        public bool student_active { get; set; }
    
        public virtual ICollection<result> results { get; set; }
    }
}
