//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sub_district
    {
        public sub_district()
        {
            this.admission_student_address = new HashSet<admission_student_address>();
            this.admission_student_address1 = new HashSet<admission_student_address>();
        }
    
        public int sub_district_id { get; set; }
        public string sub_district_name { get; set; }
        public int district_id { get; set; }
    
        public virtual ICollection<admission_student_address> admission_student_address { get; set; }
        public virtual ICollection<admission_student_address> admission_student_address1 { get; set; }
        public virtual district district { get; set; }
    }
}
