//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subject_category
    {
        public subject_category()
        {
            this.subjects = new HashSet<subject>();
        }
    
        public int subject_category_id { get; set; }
        public int department_id { get; set; }
        public string subject_category_name { get; set; }
    
        public virtual department_name department_name { get; set; }
        public virtual ICollection<subject> subjects { get; set; }
    }
}
