//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher_department
    {
        public teacher_department()
        {
            this.teachers = new HashSet<teacher>();
        }
    
        public int teacher_department_id { get; set; }
        public string teacher_department_name { get; set; }
    
        public virtual ICollection<teacher> teachers { get; set; }
    }
}
