//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher
    {
        public int teacher_id { get; set; }
        public string teacher_full_name { get; set; }
        public string teacher_degination { get; set; }
        public string teacher_eduaction { get; set; }
        public string teacher_image { get; set; }
        public System.DateTime teacher_join_date { get; set; }
        public int teacher_department_id { get; set; }
        public bool teacher_active { get; set; }
        public string teacher_address { get; set; }
        public string teacher_mobile_number { get; set; }
        public string teacher_email { get; set; }
    
        public virtual teacher_department teacher_department { get; set; }
    }
}
